### ISSUE TITLE
 yices_c.h does not exist.

### ISSUE THREAD

**Issue by tll1945** [fbrausse/smtlib2parser#1]
The  head file "yices_c.h" in smtlib2yices.h cannot been found. I search all yies's versions and yices_c.h does not exist.

**Comment by fbrausse** [comment]
Hi,
as the header file says, it assumes the quite old Yices in version 1. The archives distributed on http://yices.csl.sri.com/old/download-yices1.html contain `yices_c.h`. That part of the parser is just an example on how to use it.
